const names = [{
    "id": 1,
    "first_name": "Amalee",
    "last_name": "Lamberts",
    "email": "alamberts0@eventbrite.com",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Tiebout",
    "last_name": "O'Gleasane",
    "email": "togleasane1@mashable.com",
    "gender": "Male"
  }, {
    "id": 3,
    "first_name": "Gilles",
    "last_name": "Pendrid",
    "email": "gpendrid2@xrea.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Elbert",
    "last_name": "Piddocke",
    "email": "epiddocke3@businesswire.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Denys",
    "last_name": "Losemann",
    "email": "dlosemann4@squidoo.com",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Chrissy",
    "last_name": "Klejna",
    "email": "cklejna5@imgur.com",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Cherida",
    "last_name": "Kaman",
    "email": "ckaman6@nature.com",
    "gender": "Female"
  }, {
    "id": 8,
    "first_name": "Marieann",
    "last_name": "Brickdale",
    "email": "mbrickdale7@moonfruit.com",
    "gender": "Female"
  }, {
    "id": 9,
    "first_name": "Lizbeth",
    "last_name": "Gilgryst",
    "email": "lgilgryst8@zdnet.com",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Beitris",
    "last_name": "Feeley",
    "email": "bfeeley9@alibaba.com",
    "gender": "Female"
  }, {
    "id": 11,
    "first_name": "Jo",
    "last_name": "Starbuck",
    "email": "jstarbucka@devhub.com",
    "gender": "Female"
  }, {
    "id": 12,
    "first_name": "Stoddard",
    "last_name": "Heild",
    "email": "sheildb@slate.com",
    "gender": "Female"
  }, {
    "id": 13,
    "first_name": "Bernelle",
    "last_name": "Cockroft",
    "email": "bcockroftc@umich.edu",
    "gender": "Female"
  }, {
    "id": 14,
    "first_name": "Anne-marie",
    "last_name": "Crame",
    "email": "acramed@devhub.com",
    "gender": "Female"
  }, {
    "id": 15,
    "first_name": "Kaylil",
    "last_name": "Waters",
    "email": "kwaterse@sohu.com",
    "gender": "Female"
  }, {
    "id": 16,
    "first_name": "Chevalier",
    "last_name": "Longson",
    "email": "clongsonf@wikispaces.com",
    "gender": "Male"
  }, {
    "id": 17,
    "first_name": "Amery",
    "last_name": "Howle",
    "email": "ahowleg@pen.io",
    "gender": "Male"
  }, {
    "id": 18,
    "first_name": "Kimmie",
    "last_name": "Henriksson",
    "email": "khenrikssonh@themeforest.net",
    "gender": "Female"
  }, {
    "id": 19,
    "first_name": "Guinna",
    "last_name": "Phelp",
    "email": "gphelpi@yale.edu",
    "gender": "Female"
  }, {
    "id": 20,
    "first_name": "Sydney",
    "last_name": "Jerzyk",
    "email": "sjerzykj@dyndns.org",
    "gender": "Female"
  }, {
    "id": 21,
    "first_name": "Wynny",
    "last_name": "Whye",
    "email": "wwhyek@bandcamp.com",
    "gender": "Female"
  }, {
    "id": 22,
    "first_name": "Marissa",
    "last_name": "Neggrini",
    "email": "mneggrinil@umn.edu",
    "gender": "Female"
  }, {
    "id": 23,
    "first_name": "Miles",
    "last_name": "Arent",
    "email": "marentm@cnbc.com",
    "gender": "Male"
  }, {
    "id": 24,
    "first_name": "Robinetta",
    "last_name": "Theuss",
    "email": "rtheussn@deliciousdays.com",
    "gender": "Female"
  }, {
    "id": 25,
    "first_name": "Garnette",
    "last_name": "Westcot",
    "email": "gwestcoto@slideshare.net",
    "gender": "Female"
  }]

  export default names;